version: '2'
services:
  namenode:
    build: ./hdfs
    image: hdfsnamenode
    container_name: namenode
    environment:
        - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        - CLUSTER_NAME=hadooptest
    ports:
        - "9870:9870"
        - "9000:9000"
    volumes:
    - D:/MLProject:/opt/hadoopspark
    
  datanode:
        build: ./hdfs/datanode
        image: hdfsdatanode
        container_name: datanode
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        volumes:
            - D:/MLProject:/opt/hadoopspark
networks:
        default:
            external:
                name: MLSpark


