version: '2'
services:

  malwerml:
    build: ./ml
    image: ml:latest
    container_name: malwerml
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"

    volumes:
      - ./ml/notebooks:/home/jovyan/work/notebooks/
      
    environment:
        - SPARK_MASTER_NAME=spark-master
        - SPARK_MASTER_PORT=7077
        - SPARK_APPLICATION_PYTHON_LOCATION=/app/app.py
        - MALMODEL=hdfs://namenode:9000/model
        - RANSOMWARE=hdfs://namenode:9000/data/Ransomware/*.csv
        - ADWARE=hdfs://namenode:9000/data/Adware/*.csv
        - ENABLE_INIT_DAEMON=false
    links:
        - spark-master
  spark-master:
    image: bde2020/spark-master:3.1.2-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.1.2-hadoop3.2
    container_name: spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - ENABLE_INIT_DAEMON_STEP=false

    depends_on:
      - spark-master
    ports:
      - "8081:8081"
  spark-worker-2:
    image: bde2020/spark-worker:3.1.2-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - ENABLE_INIT_DAEMON_STEP=false

networks:
        default:
            external:
                name: MLSpark


